name: box2d
version: 0.1.6
author: Dominic Hamon <dominic@google.com>
description: A port of the popular Box2D physics engine to Dart.
homepage: http://github.com/dart-lang/dart-box2d
dev_dependencies:
  args: any
  browser: any
