name: box2d
version: 0.1.4
description: A port of the popular Box2D physics engine to Dart.
author: Dominic Hamon <dominic@google.com>
homepage: http://github.com/google/dartbox2d
dependencies:
  vector_math: any
  unittest: any
dev_dependencies:
  args: any
